export const mockUsers = [
  { 
    id: 1, 
    name: "John Doe", 
    email: "john@example.com", 
    phone: "+1 234 567 890", 
    subscription: "Monthly", 
    status: "active", 
    joinDate: "2024-01-15",
    healthProfile: {
      primaryConcern: "Lower back pain",
      painIntensity: 6,
      priorTreatments: "Physiotherapy, Massage",
      medicalHistory: "Hypertension, previous back injury",
      allergies: "Penicillin",
      medications: "Lisinopril 10mg daily",
      emergencyContact: "Jane Doe (Spouse) - +1 234 567 891",
      additionalNotes: "Patient responds well to manual therapy techniques. Avoid deep tissue massage on left side."
    }
  },
  { 
    id: 2, 
    name: "Emily Parker", 
    email: "emily@example.com", 
    phone: "+1 234 567 891", 
    subscription: "Weekly", 
    status: "active", 
    joinDate: "2024-02-20",
    healthProfile: {
      primaryConcern: "Knee pain",
      painIntensity: 4,
      priorTreatments: "Physical therapy, knee brace",
      medicalHistory: "Previous ACL surgery",
      allergies: "Sulfa drugs",
      medications: "Ibuprofen as needed",
      emergencyContact: "Michael Parker (Father) - +1 234 567 892",
      additionalNotes: "Recent improvement in range of motion. Continue strengthening exercises."
    }
  },
  { 
    id: 3, 
    name: "Mike Wilson", 
    email: "mike@example.com", 
    phone: "+1 234 567 892", 
    subscription: "None", 
    status: "inactive", 
    joinDate: "2024-01-10",
    healthProfile: {
      primaryConcern: "Neck stiffness",
      painIntensity: 3,
      priorTreatments: "Chiropractic care",
      medicalHistory: "Mild scoliosis",
      allergies: "None known",
      medications: "None",
      emergencyContact: "Lisa Wilson (Wife) - +1 234 567 893",
      additionalNotes: "Improving with stretching exercises. Needs ergonomic assessment."
    }
  },
  { 
    id: 4, 
    name: "Anna Smith", 
    email: "anna@example.com", 
    phone: "+1 234 567 893", 
    subscription: "Monthly", 
    status: "active", 
    joinDate: "2024-03-05",
    healthProfile: {
      primaryConcern: "Shoulder impingement",
      painIntensity: 5,
      priorTreatments: "Corticosteroid injection",
      medicalHistory: "Diabetes Type 2",
      allergies: "Latex",
      medications: "Metformin 500mg twice daily",
      emergencyContact: "Tom Smith (Brother) - +1 234 567 894",
      additionalNotes: "Significant improvement after injection. Continue with strengthening program."
    }
  },
  { 
    id: 5, 
    name: "Robert Brown", 
    email: "robert@example.com", 
    phone: "+1 234 567 894", 
    subscription: "Expired", 
    status: "active", 
    joinDate: "2023-12-01",
    healthProfile: {
      primaryConcern: "Hip pain",
      painIntensity: 7,
      priorTreatments: "Hip replacement surgery",
      medicalHistory: "Arthritis, previous hip replacement on right side",
      allergies: "NSAIDs",
      medications: "Acetaminophen as needed",
      emergencyContact: "Patricia Brown (Daughter) - +1 234 567 895",
      additionalNotes: "Managing well post-surgery. Needs balance training to prevent falls."
    }
  },
  { 
    id: 6, 
    name: "Lisa Anderson", 
    email: "lisa@example.com", 
    phone: "+1 234 567 895", 
    subscription: "Monthly", 
    status: "active", 
    joinDate: "2024-02-28",
    healthProfile: {
      primaryConcern: "Ankle sprain",
      painIntensity: 2,
      priorTreatments: "RICE protocol, physical therapy",
      medicalHistory: "Previous ankle sprains",
      allergies: "None known",
      medications: "None",
      emergencyContact: "James Anderson (Husband) - +1 234 567 896",
      additionalNotes: "Nearly back to normal activity level. Focus on proprioception exercises."
    }
  },
  { 
    id: 7, 
    name: "David Lee", 
    email: "david@example.com", 
    phone: "+1 234 567 896", 
    subscription: "Daily", 
    status: "active", 
    joinDate: "2024-03-10",
    healthProfile: {
      primaryConcern: "Wrist pain",
      painIntensity: 4,
      priorTreatments: "Wrist brace, ergonomic changes",
      medicalHistory: "Carpal tunnel syndrome",
      allergies: "Adhesive tape",
      medications: "None",
      emergencyContact: "Sophia Lee (Partner) - +1 234 567 897",
      additionalNotes: "Responding well to ergonomic adjustments. Continue with stretching exercises."
    }
  },
  { 
    id: 8, 
    name: "Sarah Taylor", 
    email: "sarah@example.com", 
    phone: "+1 234 567 897", 
    subscription: "None", 
    status: "inactive", 
    joinDate: "2024-01-25",
    healthProfile: {
      primaryConcern: "Headaches",
      painIntensity: 5,
      priorTreatments: "Stress management, massage",
      medicalHistory: "Migraine history",
      allergies: "Aspirin",
      medications: "Propranolol for prevention",
      emergencyContact: "Mark Taylor (Brother) - +1 234 567 898",
      additionalNotes: "Stress-related headaches. Consider referral to stress management specialist."
    }
  },
];

export const mockServices = [
  {
    id: 1,
    name: "Orthopedic Physiotherapy",
    description: "Treatment for bones, joints, muscles, ligaments, and post-surgery rehabilitation.",
    price: 600,
    duration: "60 min",
    image: "https://images.unsplash.com/photo-1559757175-5700dde675bc",
    category: "Physiotherapy",
    status: "active",
  },
  {
    id: 2,
    name: "Neuro Physiotherapy",
    description: "Rehabilitation for neurological conditions like stroke, paralysis, and Parkinson’s disease.",
    price: 700,
    duration: "60 min",
    image: "https://images.unsplash.com/photo-1606206873764-fd15e242df52",
    category: "Physiotherapy",
    status: "active",
  },
  {
    id: 3,
    name: "Sports Physiotherapy",
    description: "Injury prevention, treatment, and recovery for athletes and sports-related conditions.",
    price: 800,
    duration: "60 min",
    image: "https://images.unsplash.com/photo-1599058917212-d750089bc07e",
    category: "Sports",
    status: "active",
  },
  {
    id: 4,
    name: "Pediatric Physiotherapy",
    description: "Physiotherapy care for infants and children with developmental or physical conditions.",
    price: 650,
    duration: "45 min",
    image: "https://images.unsplash.com/photo-1600959907703-125ba1374a12",
    category: "Pediatric",
    status: "active",
  },
  {
    id: 5,
    name: "Maternity Physiotherapy",
    description: "Physiotherapy for pregnancy, postnatal recovery, and women’s health.",
    price: 700,
    duration: "60 min",
    image: "https://images.unsplash.com/photo-1559757175-5700dde675bc",
    category: "Women Care",
    status: "active",
  },
  {
    id: 6,
    name: "Podiatry Physiotherapy",
    description: "Foot, ankle, and lower limb pain treatment and posture correction.",
    price: 600,
    duration: "45 min",
    image: "https://images.unsplash.com/photo-1603398938378-e54eab446dde",
    category: "Podiatry",
    status: "active",
  },
  {
    id: 7,
    name: "Chiropractic",
    description: "Manual spine and joint adjustments to reduce pain and improve mobility.",
    price: 900,
    duration: "30 min",
    image: "https://images.unsplash.com/photo-1599058918144-1ffabb6ab9a0",
    category: "Chiropractic",
    status: "active",
  },
  {
    id: 8,
    name: "Weight Management",
    description: "Personalized programs for healthy weight loss, fitness, and lifestyle improvement.",
    price: 500,
    duration: "45 min",
    image: "https://images.unsplash.com/photo-1558611848-73f7eb4001a1",
    category: "Wellness",
    status: "active",
  },
  {
    id: 9,
    name: "Cosmetic & Hair Care",
    description: "Advanced cosmetic treatments and professional hair care services.",
    price: 1000,
    duration: "60 min",
    image: "https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9",
    category: "Cosmetic",
    status: "active",
  },
  {
    id: 10,
    name: "Home Service",
    description: "Physiotherapy and wellness treatments provided at the comfort of your home.",
    price: 1200,
    duration: "60 min",
    image: "https://images.unsplash.com/photo-1584515933487-779824d29309",
    category: "Home Care",
    status: "active",
  },
];

  

export const mockBookings = [
  {
    id: 1,
    serviceId: 1,
    serviceName: "Physical Therapy",
    clientId: 1,
    clientName: "John Doe",
    therapistId: 1,
    therapistName: "Dr. Sarah Johnson",
    date: "2024-03-25",
    time: "10:00 AM",
    status: "confirmed",
    notes: "Patient has lower back pain, bring medical records."
  },
  {
    id: 2,
    serviceId: 2,
    serviceName: "Massage Therapy",
    clientId: 2,
    clientName: "Emily Parker",
    therapistId: 2,
    therapistName: "Dr. Michael Chen",
    date: "2024-03-26",
    time: "2:00 PM",
    status: "confirmed",
    notes: "Focus on shoulder and neck tension."
  },
  {
    id: 3,
    serviceId: 3,
    serviceName: "Acupuncture",
    clientId: 3,
    clientName: "Mike Wilson",
    therapistId: 3,
    therapistName: "Dr. Lisa Williams",
    date: "2024-03-27",
    time: "11:30 AM",
    status: "pending",
    notes: "First appointment, discuss medical history."
  },
  {
    id: 4,
    serviceId: 1,
    serviceName: "Physical Therapy",
    clientId: 4,
    clientName: "Anna Smith",
    therapistId: 4,
    therapistName: "Dr. James Brown",
    date: "2024-03-28",
    time: "9:00 AM",
    status: "cancelled",
    notes: "Patient cancelled due to scheduling conflict."
  },
  {
    id: 5,
    serviceId: 5,
    serviceName: "Nutrition Counseling",
    clientId: 5,
    clientName: "Robert Brown",
    therapistId: 1,
    therapistName: "Dr. Sarah Johnson",
    date: "2024-03-29",
    time: "1:00 PM",
    status: "confirmed",
    notes: "Follow-up appointment for meal plan review."
  },
];
